def configurar_nivel(juego,dificult):
    #colocar muro y queso segun la diuficultad
    #modo facil
    if dificult == "1":
        # colocar queso
        juego.colocar_queso(8, 6)
        # colocar los muros
        juego.colocar_muro(0,0)
        juego.colocar_muro(1,0)
        juego.colocar_muro(0,1)
        juego.colocar_muro(14,0)
        juego.colocar_muro(15,0)
        juego.colocar_muro(15,1)
        juego.colocar_muro(2,2)
        juego.colocar_muro(3,2)
        juego.colocar_muro(2,3)
        juego.colocar_muro(6,2)
        juego.colocar_muro(7,2)
        juego.colocar_muro(8,2)
        juego.colocar_muro(11,2)
        juego.colocar_muro(12,2)
        juego.colocar_muro(12,3)
        juego.colocar_muro(7,4)
        juego.colocar_muro(8,4)
        juego.colocar_muro(5,5)
        juego.colocar_muro(6,5)
        juego.colocar_muro(9,5)
        juego.colocar_muro(0,6)
        juego.colocar_muro(10,6)
        juego.colocar_muro(11,6)
        juego.colocar_muro(15,6)
        juego.colocar_muro(0,8)
        juego.colocar_muro(1,8)
        juego.colocar_muro(13,8)
        juego.colocar_muro(14,8)

        print("Mapa cargado: LA ZONA URBANA (Medio)")
        
    #para el nivel medio
    elif dificult == "2":
        juego.colocar_queso(0, 8)
        for y in range(3, 6):
            juego.colocar_muro(5, y)
            juego.colocar_muro(6, y)
        print("Mapa cargado: EL BOSQUE (Medio)")
    #para el nivel dificil
    elif dificult == "3":
        juego.colocar_queso(3,2)
        juego.colocar_muro(1,1)
        juego.colocar_muro(2,1)
        juego.colocar_muro(3,1)
        juego.colocar_muro(2,3)
        juego.colocar_muro(3,3)
        juego.colocar_muro(4,3)
        juego.colocar_muro(5,3)
        juego.colocar_muro(6,3)
        juego.colocar_muro(6,4)
        juego.colocar_muro(6,5)
        juego.colocar_muro(4,5)
        juego.colocar_muro(3,5)
        juego.colocar_muro(2,5)
        juego.colocar_muro(1,5)
        juego.colocar_muro(3,6)
        juego.colocar_muro(3,7)
        juego.colocar_muro(2,7)
        juego.colocar_muro(5,7)
        juego.colocar_muro(6,7)
        juego.colocar_muro(7,7)
        juego.colocar_muro(8,7)
        juego.colocar_muro(8,6)
        juego.colocar_muro(8,5)
        juego.colocar_muro(6,0)
        juego.colocar_muro(6,1)
        juego.colocar_muro(6,1)
        juego.colocar_muro(9,1)
        juego.colocar_muro(11,0)
        juego.colocar_muro(11,1)
        juego.colocar_muro(11,3)
        juego.colocar_muro(11,4)
        juego.colocar_muro(11,5)
        juego.colocar_muro(10,6)
        juego.colocar_muro(13,1)
        juego.colocar_muro(13,2)
        juego.colocar_muro(13,4)
        juego.colocar_muro(13,5)
        juego.colocar_muro(12,8)
        juego.colocar_muro(11,8)
        juego.colocar_muro(10,8)
        juego.colocar_muro(13,8)
        juego.colocar_muro(15,8)
        juego.colocar_muro(14,8)
        juego.colocar_muro(14,2)
        juego.colocar_muro(14,3)
        juego.colocar_muro(14,4)

        print("Mapa cargado: EL LABERINTO (Difícil)")